# Generated by Django 2.1.11 on 2019-10-20 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191019_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='date',
            new_name='date_modified',
        ),
        migrations.AddField(
            model_name='link',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
