# Generated by Django 2.1.11 on 2019-11-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191106_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='NoteComment',
        ),
    ]
