# Generated by Django 2.1.11 on 2019-11-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191106_1931'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notecomment',
            table='note_comment',
        ),
    ]
