# Generated by Django 2.1.11 on 2019-11-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191106_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='main.NoteComment'),
        ),
    ]
