# Generated by Django 2.1.11 on 2019-11-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191107_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='main.NoteComment'),
        ),
    ]
