# Generated by Django 2.1.11 on 2019-11-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191113_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='type',
            field=models.CharField(choices=[('ACTIVATION', 'activation'), ('PASSWORD_RESET', 'password_reset')], default='activation', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='secret_key',
            field=models.CharField(default='32ad672424fdb0d8cd6e669d365dea10', max_length=255),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userconfirmation',
            unique_together={('user', 'type')},
        ),
    ]
