# Generated by Django 2.1.11 on 2019-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191114_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='secret_key',
            field=models.CharField(default='44ffda95bb6080b14fd7143b9432bb6d', max_length=255),
        ),
    ]
