# Generated by Django 2.1.11 on 2019-11-15 13:20

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191114_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='secret_key',
            field=models.CharField(default=main.utils.get_random_key, max_length=255),
        ),
    ]
