#!/usr/bin/env bash

NAME="Storageofknowledge"                                      # Name of the application
DJANGODIR=/webapps/storageofknowledge/app/storageofknowledge            # Django project directory
SOCKFILE=/webapps/storageofknowledge/app/run/gunicorn.sock     # we will communicte using this unix socket
LOGDIR=/webapps/storageofknowledge/app/log                     # Logs directory
VENV=/webapps/storageofknowledge/env                           # virtual environment root path
USER=storageofknowledge                                          # the user to run as
GROUP=webapps                                         # the group to run as
NUM_WORKERS=3                                         # how many worker processes should Gunicorn spawn
DJANGO_WSGI_MODULE=storageofknowledge.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source $VENV/bin/activate
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Create the logs directory if it doesn't exist
test -d $LOGDIR || mkdir -p $LOGDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $VENV/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name "$NAME" \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-